[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
evm_version = "cancun"
remappings = ["starkware/=build-artifacts/lib/cairo-lang/src/starkware/"]
optimizer = true
optimizer_runs = 200
